### ISSUE TITLE
1.4.2 interface breakage

### ISSUE THREAD

**Issue by bpoldrack** [Lykos153/AnnexRemote#21]
Hi @Lykos153,

we (https://github.com/datalad/datalad) use `AnnexRemote` as a dependency. So, first of all: Thank you for making it! Second, however, changing public attributes breaks things. In this case, it was `Master.protocol` -> `Master._protocol` that hit us. That's not incredibly terrible, but it would be nice if such breakage was announced in the release notes or - even better - would come with a telling deprecation error. Basically just want to let you know, that you have (otherwise happy) users, whose stuff (and CI runs) will fail on such things.

Thanks again and keep it up!

**Comment by Lykos153** [comment]
Thanks for pointing that out! And sorry I didn't spot that. The truth is: `Protocol` was never intended to be part of the public API and when I finally got round to make the docs for this project I spotted my mistake and "fixed" it... Not noticing that - without any documentation - nobody could know that it's not supposed to be used. And all the tests are written only for the intentionally public part, so they didn't complain either.
Anyway, `Protocol` is back and it will be for at least v1.x.x.

Also, I'm very happy to hear that `AnnexRemote` is useful to somebody! :)
