### ISSUE TITLE
17 test failures on Listen()

### ISSUE THREAD

**Issue by gravndal** [Lykos153/AnnexRemote#25]
Hi,

I'm trying to update the annexremote package on NixOS to 1.4.4, and getting 17 test failures on Listen().
Build log: https://gist.github.com/gravndal/6683fdcd681cfec94e059f5002524e01

Are some tests out of date wrt https://github.com/Lykos153/AnnexRemote/commit/4a634cb72f56fea508f49e51267d20c86f7cbaa1?

**Comment by Lykos153** [comment]
You're right! I'm fixing it.

**Comment by Lykos153** [comment]
Fixed in 5bdc6d5fa6d2936985cb58e053bdf2afa2912e8b
