### ISSUE TITLE
RFE: move away from deprecated nose (to pytest?)

### ISSUE THREAD

**Issue by sanjayankur31** [Lykos153/AnnexRemote#32]
# Feature
nose is deprecated, so it'll be good to move to another testing tool, perhaps py.test.

# Motivation
nose is deprecated upstream (the last commit was in 2016.) and is also being deprecated in Fedora.

https://github.com/nose-devs/nose/commits/master

It is still in use in the repo but only to run tests, so moving to pytests should be quite simple here.

The nose website says:

https://nose.readthedocs.io/en/latest/

"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2."

Deprecation of nose in Fedora: https://fedoraproject.org/wiki/Changes/DeprecateNose

Alternatives
py.test or nose2 (but nose2 doesn't seem to be at par with nose or py.test)

**Comment by Lykos153** [comment]
Absolutely! I've had moving to py.test in the back of my mind for a while but... well, time.

**Comment by yarikoptic** [comment]
I would vote for pytest. Let us know if you need help.  Time goes and `nose` is getting actively deprecated in distributions e.g. Debian

**Comment by sanjayankur31** [comment]
There are helper tools like this one that may reduce the workload, but it really depends on how advanced the nose usage here is:

https://github.com/pytest-dev/nose2pytest

**Comment by yarikoptic** [comment]
done in #80
