### ISSUE TITLE
Test error with Python3.10

### ISSUE THREAD

**Issue by tillea** [Lykos153/AnnexRemote#33]
Hi,
there is a [bug report](https://bugs.debian.org/1002340) against the Debian packaged version 1.5.0.  I've upgraded the Debian packaging to 1.6.0 but the issue persists:

      File "/build/annexremote-1.6.0/.pybuild/cpython3_3.10_annexremote/build/tests/test_GitAnnexRequestMessages.py", line 305, in TestExport_MissingName
        self.assertEqual(utils.last_buffer_line(self.output), "ERROR do_EXPORT() missing 1 required positional argument: 'name'")
    AssertionError: "ERROR Protocol.do_EXPORT() missing 1 required positional argument: 'name'" != "ERROR do_EXPORT() missing 1 required positional argument: 'name'"
    - ERROR Protocol.do_EXPORT() missing 1 required positional argument: 'name'
    ?       ---------
    + ERROR do_EXPORT() missing 1 required positional argument: 'name'

    ======================================================================
    FAIL: TestRemoveexportdirectory_MissingDirectory (test_GitAnnexRequestMessages.TestGitAnnexRequestMessagesExporttree)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/annexremote-1.6.0/.pybuild/cpython3_3.10_annexremote/build/tests/test_GitAnnexRequestMessages.py", line 423, in TestRemoveexportdirectory_MissingDirectory
        self.assertEqual(utils.last_buffer_line(self.output), "ERROR do_REMOVEEXPORTDIRECTORY() missing 1 required positional argument: 'name'")
    AssertionError: "ERROR Protocol.do_REMOVEEXPORTDIRECTORY() missi[37 chars]ame'" != "ERROR do_REMOVEEXPORTDIRECTORY() missing 1 requ[28 chars]ame'"
    - ERROR Protocol.do_REMOVEEXPORTDIRECTORY() missing 1 required positional argument: 'name'
    ?       ---------
    + ERROR do_REMOVEEXPORTDIRECTORY() missing 1 required positional argument: 'name'

    ----------------------------------------------------------------------
    Ran 134 tests in 0.199s

    FAILED (failures=2)

Kind regards, Andreas.

**Comment by Lykos153** [comment]
#29 would fix this but also break compatibility with all versions <3.10. I hope I find the time to look into this soon.
