### ISSUE TITLE
Please publish 1.6.0 on pypi

### ISSUE THREAD

**Issue by mih** [Lykos153/AnnexRemote#34]
PyPi has 1.5.0 as the latest release (not available as a github release, it seems), but Debian already has the 1.6.0 -- which is also the latest here.

Thx!

**Comment by Lykos153** [comment]
Thanks for bringing this up and sorry for the long delay. I published the current version yesterday and added a gh action to publish tags and releases automatically, so this shouldn't become an issue in the future.

**Comment by mih** [comment]
Great, thx!
