### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by notestaff** [Lykos153/AnnexRemote#6]
@Lykos153 Can you tag a new release, that would incorporate the fixes since 1.2.0 ( https://github.com/Lykos153/AnnexRemote/compare/v1.2.0...master )?  I'm making a conda-forge recipe ( https://conda-forge.org/ ) for AnnexRemote, and it would be good if the release with the fixes could be included.  Thanks!

**Comment by notestaff** [comment]
@Lykos153 annexremote is now installable through conda-forge.  It'd still be good to tag a new release with the current fixes.  Also let me know if I can add you as a co-maintainer of the conda-forge recipe.

**Comment by Lykos153** [comment]
Done! Sorry for the delay. Thanks for creating the recipe. I would currently decline the offer to be added as a co-maintainer as I don't use conda myself and don't have the capacity to maintain it at the moment.

**Comment by notestaff** [comment]
@Lykos153 thanks!  can you also update it on pip?  If not I can change the recipe to fetch from github directly.

**Comment by Lykos153** [comment]
I did that yesterday. PyPI generates a new URL for every upload, so you'll need to copy & paste it from there: https://pypi.org/project/annexremote/
