### ISSUE TITLE
auto-mate releases?

### ISSUE THREAD

**Issue by yarikoptic** [Lykos153/AnnexRemote#69]
any objections to automate releases using  https://github.com/intuit/auto ?  It helps to automate release to pypi and generation of changelog from PR titles.
the known shortcoming is E2BIG fiasco whenever changelog grows too large -- mitigated by "release often" which is IMHO good to have.  Example projects I am involved with which using it

- https://github.com/dandi/dandi-cli/blob/master/CHANGELOG.md
- https://github.com/datalad/datalad-container/blob/master/CHANGELOG.md

In datalad itself we created custom https://github.com/datalad/release-action which uses https://github.com/nedbat/scriv/ for *better* control over changelog entries. But IMHO it would be overkill/extra-burden here.

- [x] `Created labels: major, minor, patch, skip-release, internal, documentation, tests, dependencies, performance`
- [x] Label PRs merged  since v1.6.0
- [ ] see what else to be done
- [x] make sure changelog is in appropriate format
- [x] add / replace current `.github/workflows/python-publish.yml which would do the auto thing (#73)

**Comment by Lykos153** [comment]
No objections, I like the idea!
