### ISSUE TITLE
python 2.7 compatibility

### ISSUE THREAD

**Issue by notestaff** [Lykos153/AnnexRemote#8]
@Lykos153 How hard would it be to make AnnexRemote compatible with python2.7?  Some packages require python2.7 , which makes it impossible to use both these packages and AnnexRemote-based external special remote implementations together.

**Comment by Lykos153** [comment]
Probably not that hard. I'm having a look in the evening. However, I don't want to put too much effort into it, as 2.7 reaches end of life in less than twelve months. I'm always accepting pull requests though.

**Comment by notestaff** [comment]
#12

@Lykos153 thanks for making py27 work.  can you tag a new release with it, and upload the corresponding PYPI package, for conda-forge recipe purposes?

**Comment by Lykos153** [comment]
Done ;)
