### ISSUE TITLE
Autorelease failed due to branch protection

### ISSUE THREAD

**Issue by yarikoptic** [Lykos153/AnnexRemote#85]
```
 ! [remote rejected] master -> master (protected branch hook declined)
```
where it tried to push the updated master with the changelog and the tag later. I will disable branch protection, close this issue, and will try releasing again

**Comment by yarikoptic** [comment]
ah -- I can't remove branch protection. @Lykos153 - please apply your super powers.

**Comment by yarikoptic** [comment]
ping @Lykos153

**Comment by Lykos153** [comment]
Should be disabled now
